name: TheDungeon
version: '${version}'
main: t.me.p1azmer.plugin.dungeons.DungeonPlugin
api-version: '1.17'
author: "plazmer"
description: "Dungeons - Drop random objects at random locations in the worlds"
depend:
  - PLAZMER-ENGINE
softdepend:
  - HolographicDisplays
  - DecentHolograms
  - WorldEdit
  - WorldGuard
  - ItemsAdder
  - MMOItems
  - GriefDefender
  - GriefPrevention
  - FastAsyncWorldEdit
  - PlaceholderAPI
  - KingdomsX
  - PartyAndFriends
  - Towny
